### ISSUE TITLE
Some thinking.

### ISSUE THREAD

**Issue by 0b1kn00b** [haxetink/tink_typecrawler#1]
I can see there's probably no good way of doing a general handler without using the whole type representation somewhere, but right now, you can't subclass or wrap genType,, because reject is already handled. If you went to a Chunk implementation (Val || End(?Error) || Nil)  Crawler becomes extendable. End() could handle specific rejections, and Nil for 'nothing wrong, but nothing found'.

What do you think?

**Comment by back2dos** [comment]
Yep. Shortly after publishing the lib I hit the same limitation ;)

**Comment by 0b1kn00b** [comment]
Here it is (wrapped)[https://github.com/0b1kn00b/tink_typecrawler/commit/c05dfb7cdea4e0a8f20c5dd11731c31ed6ddad5d], any tests about?

**Comment by back2dos** [comment]
Sorry, I had already started down another road. Can you please check that it works for you? Otherwise please feel free to open another issue to specify the use case not covered.

**Comment by 0b1kn00b** [comment]
No prob,

I'm looking at clone / eq / ord implementations at macro time.
