### ISSUE TITLE
Crawler chokes on private types / typedef

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_typecrawler#17]
Trying to fix https://github.com/haxetink/tink_validation/issues/12, when I add these lines to `rescue()`:

```haxe
case _.getID() => 'haxe._Int64.___Int64':
  Some(macro if(!haxe.Int64.is(value)) throw tink.validation.Error.UnexpectedType(path, String, value) else value);
```

It fails with:
```
Type not found : haxe._Int64.Int64
```

I think somewhere inside the crawler it is converting an abstract's underlying `Type` to `ComplexType` then back to a `Type`.
In the latter process if the underlying type itself is declared with `private` it will fail.

Or it is related to `typedef`, because the error is the same as what described in https://github.com/haxetink/tink_web/issues/30

**Comment by kevinresol** [comment]
OK here is how it fails, see the generated field:

```haxe
function parse1(value:haxe._Int64.Int64.__Int64) return if (!haxe.Int64.is(value)) throw tink.validation.Error.UnexpectedType(path, String, value) else value;
```

note the type of `value`

**Comment by kevinresol** [comment]
So there are two problems here:

1. the complex type passed to `placeholder` should be the original type, not the followed type
2. tink_macro's `toComplex()` seems to be problematic, it should be `haxe.Int64.__Int64` instead of `haxe._Int64.Int64.__Int64`

**Comment by volth** [comment]
```'haxe._Int64.___Int64'``` <- this is target dependent. On Java it is different

**Comment by volth** [comment]
Another tricky point is there could be, say after MSGPACK unpacking (js target)
```
var dynamic = {
  a: { high: 1, low: 42 } /* was serialized as Int64 because it is big  */, 
  b: 42 /* was serialized as Int because is is too small */
}
```

and
```
var x: {a: Int64, b: Int64} = Validation.extract(dynamic);
```
suppose to be valid

**Comment by kevinresol** [comment]
> 'haxe._Int64.___Int64' <- this is target dependent. On Java it is different

macro is target-aware. My example is on js target, wishing to demonstrate the complex type conversion problem in tink_macro.

**Comment by kevinresol** [comment]
About the MSGPACK thing: we can possibly do that by writing platform-specific runtime checks, like:

```haxe
if(Reflect.isObject(value) && Reflect.hasField(value, 'high') && Reflect.hasField(value, 'low') && Std.is(Reflect.field(value, 'high'), Int) && Std.is(Reflect.field(value, 'low'), Int))
  return Int64.make(Reflect.field(value, 'high'), Reflect.field(value, 'low'))
```

**Comment by kevinresol** [comment]
> About the MSGPACK thing: we can possibly do that by writing platform-specific runtime checks, like:
> 
> if(Reflect.isObject(value) && Reflect.hasField(value, 'high') && Reflect.hasField(value, 'low') && Std.is(Reflect.field(value, 'high'), Int) && Std.is(Reflect.field(value, 'low'), Int))
>   return Int64.make(Reflect.field(value, 'high'), Reflect.field(value, 'low'))

This is fixed in https://github.com/haxetink/tink_validation/commit/469acbc07b644c1807072e03e3a50745d5b414e4

**Comment by kevinresol** [comment]
I confirm this is fixed (https://github.com/haxetink/tink_macro/commit/800891bee236b5a24a1dc04265fd3c8a37b3bb32)
