### ISSUE TITLE
Crawler.hx:23: characters 44-76 : (t : Null<Bool>) -> Null<Bool> should be Null<Bool>

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_typecrawler#19]
C:\HaxeToolkit\haxe\lib\tink_typecrawler/git/src/tink/typecrawler/Crawler.hx:23: characters 44-76 : (t : Null<Bool>) ->
Null<Bool> should be Null<Bool>?

haxe 4.2.1

tink_libs git.

**Comment by back2dos** [comment]
Hard to say what this is about. Please provide something reproducible.
