### ISSUE TITLE
Dynamic

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_typecrawler#2]
I think `Dynamic` (without type parameter) should also be handled, we may simply pass a null to `gen.dyn` and let user handle it.

``` haxe
          case TDynamic(t):

            if(t == null)
                gen.dyn(null, null);
            else
                gen.dyn(gen.dynAccess(genType(t, pos)), t.toComplex());
```

For example, tink_json's GenWriter may be changed to:

``` haxe
  static public function dyn(e, ct) 
    if(e == null) throw "Dynamic without type parameter is not supported"; // add this line
    return macro {
      var value:haxe.DynamicAccess<$ct> = value;
      $e;
    }
```

Related: https://github.com/haxetink/tink_json/issues/2

**Comment by back2dos** [comment]
Just to be clear here: plain `Dynamic` is not handled in the `Dynamic<T>` branch, but one can handle it in `rescue`. Hope that works for you.

**Comment by kevinresol** [comment]
@back2dos Thanks for the fix. Have been working on a [runtime typecheck util](https://github.com/kevinresol/anon) and this lib really helped.
Btw, do you think it is a good enough util to be added to haxetink?

**Comment by back2dos** [comment]
Oooh, very interesting! I had plans for such a thing myself, but you beat me to it :D

I'm very honored by your offer to add your code to tink. However, I must warn you that I am strongly attached to this project (i.e. tink as a whole) and the spirit I started it in - which I cannot properly verbalize to this day. Chances are that I will occasionally confront you with rather idiosyncratic decisions, that I just can't explain but "feel" to be right. From working with Nicolas, I know how frustrating this can be, so I do try hard to make it better. But still, I feel that I should caution you. Ultimately, like all approaches, collaboration has its own challenges and rewards. If you feel up to it, I'd be thrilled to welcome you aboard. If not, I understand perfectly.

Either way, your lib is really cool! ;)

**Comment by kevinresol** [comment]
In fact, it is you beat me on this. I have this idea long time ago but I just don't have the skill to "make it right". Until I meet tink_typecrawler and tink_json, which give me the tool and example to finish it.

I truly understand that software designing is actually more art than science. Since I don't have much sense in this regard, I would be more than happy to hear comments from you.

btw, I am really really impressed by how useful yet simple and elegant the tink libraries are.

**Comment by back2dos** [comment]
Well then, welcome to the club! 

And also, thank you for your kind words :)

**Comment by kevinresol** [comment]
Thanks! I transferred the repo, but  after that I am unable to access the setting page to rename it...

**Comment by back2dos** [comment]
Ok, I changed a couple of permissions. Can you please try again?

**Comment by kevinresol** [comment]
Yes, it's ok now. Btw do you have any opinion on the repo name?
