### ISSUE TITLE
A crawler that does Type->Type?

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_typecrawler#5]
I would like to generate a output type based on a input type. Useful for converting server-side types to client-side types.

Currently I can do it a bit hackily like:
`var type = Context.typeof(Crawler.genType(...).expr);`

**Comment by back2dos** [comment]
That's certainly an interesting idea. I'm not 100% sure how to go about it though. Could you provide a real-world-ish example of how you use this (I'm interested to see how input and output types look)?

**Comment by kevinresol** [comment]
Currently I have something like this. 

Say I have a `User` type on server-side:

``` haxe
typedef User = {
  id:String,
  name:String,
  @:private passwordHash:String,
}
```

and here is the overview of the macro I am using:

``` haxe
@:genericBuild(build())
class Response<T>{}

function build() {
  // 1. read the type parameter from Context.getLocalType()
  // 2. strip off those fields with @:private (this part is simplified for demo purpose, I have quite a few different metas to govern the build)
  // 3. create the type definition: {id:String, name:String}
  // 4. Context.defineType(def);
  // 5. return Context.getType(...);
}
```

And as a result:

``` haxe
Response<User> == {id:String, name:String}
```

And I use this generated type in both server-side (to generate the response) and client-side (for receiving the response) to ensure both sides conform to the same type.

My current macro works, but it is a bit messy in terms of the recursive type inspection logic. And I see this lib has some good effort done in that area so I suppose it can be tuned a bit to fit my needs 😛

**Comment by back2dos** [comment]
I think this should be quite easy to do with BuildCache, now that it's metadata-aware.
