### ISSUE TITLE
Get rid of `Function` for `anon` to unconfuse Kevin (and my self to be honest)

### ISSUE THREAD

**Issue by back2dos** [haxetink/tink_typecrawler#6]
see https://github.com/haxetink/tink_typecrawler/commit/8743ffcc5f77a3d6fc7e5884552a4efd73815696#diff-3e3ce03fa2c62d389c10d9f7a2441f2bR21

**Comment by back2dos** [comment]
@kevinresol Sorry, I decided to break a few things. I remembered why I wanted a `Function` (otherwise the type is lost and inference fails). So now instead of the `args` a `Generator` must implement [`wrap`](https://github.com/haxetink/tink_typecrawler/commit/ff14624a8a2c64ec266f7adc1a2c95885abd52b1#diff-3e3ce03fa2c62d389c10d9f7a2441f2bR12) so that you may define required arguments, return type and what not. The supplied `placeholder` will (later) be modified in place to contain the generated expression (this has to be so to deal with cycles).

**Comment by kevinresol** [comment]
This approach is actually easier to understand than before, as I have spent some time to understand what the args list means. And this may fix https://github.com/haxetink/tink_json/pull/4 as well
